### *TESTING FOR API* ###

In [8]:
import pandas as pd
import numpy as np
import joblib
from joblib import dump, load

In [9]:
data = pd.read_csv("get_around_pricing_project.csv", index_col=0)
data.head()

,model_key,mileage,engine_power,fuel,paint_color,car_type,private_parking_available,has_gps,has_air_conditioning,automatic_car,has_getaround_connect,has_speed_regulator,winter_tires,rental_price_per_day
0,Citroën,140411,100,diesel,black,convertible,True,True,False,False,True,True,True,106
1,Citroën,13929,317,petrol,grey,convertible,True,True,False,False,False,True,True,264
2,Citroën,183297,120,diesel,white,convertible,False,False,False,False,True,False,True,101
3,Citroën,128035,135,diesel,red,convertible,True,True,False,False,True,True,True,158
4,Citroën,97097,160,diesel,silver,convertible,True,True,False,False,False,True,True,183

In [10]:
predictionFeatures = {
  "model_key": "Citroën",
  "mileage":128035,
  "engine_power":135,
  "fuel": "diesel",
  "paint_color": "red",
  "car_type": "convertible",
  "private_parking_available": True,
  "has_gps": True,
  "has_air_conditioning": False,
  "automatic_car": False,
  "has_getaround_connect": True,
  "has_speed_regulator": True,
  "winter_tires": True
  }

In [11]:
citroen = pd.DataFrame(dict(predictionFeatures), index=[0])
citroen

,model_key,mileage,engine_power,fuel,paint_color,car_type,private_parking_available,has_gps,has_air_conditioning,automatic_car,has_getaround_connect,has_speed_regulator,winter_tires
0,Citroën,128035,135,diesel,red,convertible,True,True,False,False,True,True,True

In [12]:
loaded_model = load('modele2.joblib')

In [13]:
prediction = loaded_model.predict(citroen)
response = {"predictions": prediction.tolist()}

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:202: UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [14]:
response

{'predictions': [136.9580078125]}